# Generated by Django 5.1.4 on 2025-01-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='Позиция в карусели')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное фото')),
            ],
        ),
    ]
