# Generated by Django 5.1.4 on 2025-01-07 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Карусель', 'verbose_name_plural': 'Карусели'},
        ),
    ]
