# Generated by Django 5.1.4 on 2025-01-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена товара'),
        ),
    ]
